package com.easikoglu.ses.util;

public enum EmailType {
	NEW_MEMBER_WITH_REGISTERED_EMAIL,
	NEW_MEMBER,
	EMAIL_REGISTER,
	EMAIL_CANCEL,
	ORDER_SUMMARY,
	NEW_PASSWORD,
	NEW_PASSWORD_SUCCESSFUL,
	ORDER_SHIPPED;
}
